### ISSUE TITLE
Clear concept of a CLI

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#1]
Add a “Usage” section in the README file and describe a clear concept of the CLI interface.
Describe every command and key for a specific operation.

AC1: Usage section in readme file is created
AC2: CLI interface is described

**Comment by oleksandr-jr** [comment]
I created this PR, so I can't make a review and approve it. Someone else has to do it.

**Comment by oleksandr-jr** [comment]
Related to #2 
CLI structure is mentioned there.

**Comment by dRaider-bitrek** [comment]
Щось в нас не вийшло закрити PR  потрібна допомога на лекції.
