### ISSUE TITLE
[FR] Wiki

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#11]
## Description
Create wiki pages like

- Short project description
- Usage #1 
- Tech stack
- Authors

https://github.com/JavaRush-GNEW/contact-manager/wiki
## Acceptance criteria
1. Wiki pages are created.

**Comment by oleksandr-jr** [comment]
@BevzyukIvan Please, don't forget to move the ticket to “In progress” column if you already started working on it :)

**Comment by BevzyukIvan** [comment]
Thank you, I've already moved it

**Comment by dRaider-bitrek** [comment]
1. Загальний вигляд, та формат мені подобаются. 
2. У README.md оновлена інформіція, змінені приклади, це треба оновити.
3. Зараз з main гілки вже можна додати до Dependencies: 

- https://mvnrepository.com/artifact/info.picocli/picocli
- https://mvnrepository.com/artifact/org.mapstruct/mapstruct
- https://mvnrepository.com/artifact/org.projectlombok/lombok
- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind 

4. Build Tools:  IntelliJ IDEA, Maven
