### ISSUE TITLE
[FR] Code static analysis

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#13]
## Description
Implement static analysis like [codacy](https://www.codacy.com/) with minimal level of checking to make it not annoying.

## Acceptance criteria
1. Static analysis is implemented.
2. Static analysis is running in the pipeline for every PR.

**Comment by oleksandr-jr** [comment]
Implemented codacy static analysis.
Here is the [dashboard](https://app.codacy.com/gh/JavaRush-GNEW/contact-manager/dashboard) of the project.

**Comment by dRaider-bitrek** [comment]
Можно на наступному заняті пару хвилин про цю таску?

**Comment by oleksandr-jr** [comment]
@dRaider-bitrek Звісно, сьогодні поговоримо про це

**Comment by oleksandr-jr** [comment]
@dRaider-bitrek Поки можеш заглянути в [документацію](https://docs.codacy.com/getting-started/codacy-quickstart/)

**Comment by oleksandr-jr** [comment]
https://blog.codacy.com/codacy-intellij-idea-extension-now-available
