### ISSUE TITLE
Basic structure

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#2]
Create a simple UML diagram to describe basic structure and relations of model entities such as Contact book, contact, phone number, etc...

AC1: UML Diagram is created

**Comment by oleksandr-jr** [comment]
Так, я думаю цього буде достатньо.

AC1 не виконано. Треба зробити UML class діаграму.

Можеш використати https://lucid.app/
Там навіть є шаблон для UML class діаграм
![Image](https://github.com/user-attachments/assets/dc87583c-3b1d-421f-af5a-fc506dd87ca7)

**Comment by dRaider-bitrek** [comment]
![Image](https://github.com/user-attachments/assets/3ed99a91-b00d-467e-aa82-9e86cbbd933d)

https://lucid.app/   Можна туди экспортувати діаграму з IDE?

**Comment by oleksandr-jr** [comment]
Якось можна експортувати в інші застосунки, але цієї картинки цілком достатньо.
Я також думаю що варто репрезентувати email та phone у вигляді класів. А для списків використати колекції замість масивів (ArrayList / HashSet)
Це може спростити багато речей у майбутньому.

**Comment by dRaider-bitrek** [comment]
![Image](https://github.com/user-attachments/assets/8af34b4c-3189-4fce-b21f-42601771c964)
Оновлена пропозиція по стуктурі пректу: 
- Окремі класи для Email та PhoneNumber (Там моно розмістити валідацію формату) 
- Інтерфейс PhoneBookContext який має завантажувати і надавати доступ до налаштувань програми.
- Інтерфейс Contact 
- PhoneBookInterface interface через який CLI комуніує з реалізацією логіки команд.

**Comment by oleksandr-jr** [comment]
Looks good
