### ISSUE TITLE
[FR] Add the "locale" command to the CLI.

### ISSUE THREAD

**Issue by dRaider-bitrek** [JavaRush-GNEW/contact-manager#24]
## Description
Add the "locale" command to the CLI. Which will save the current locale in the settings.
Use SettingsServiceInterface.

## Dependencies
- #7 
- #16 
- #22 
- #33 

## Acceptance criteria
1. The locale command should store the current locale through the SettingsRepository interface.
2. Fixed README.md

**Comment by DenysBurduzhan** [comment]
Пришлось создавать промежуточный класс ибо из-за инициализации SettingsRepository в SettingsService ,  просило имплементировать методы. Есть ли другой подход?

**Comment by dRaider-bitrek** [comment]
> Пришлось создавать промежуточный класс ибо из-за инициализации SettingsRepository в SettingsService , просило имплементировать методы. Есть ли другой подход?

Потрібно створити клас який імплементить SettingsRepository. Ніякого коду в інтерфейсі.
