### ISSUE TITLE
[FR]Create an implementation of the interface SettingsRepository

### ISSUE THREAD

**Issue by dRaider-bitrek** [JavaRush-GNEW/contact-manager#27]
## Description
Create an implementation of the interface.
Use the jackson-databind library
Settings should be stored in the format Map<String,String> (key, value)

## Dependencies
- #22 

## Acceptance criteria

1. The setting can be saved to a file
2. The setting can be read from a file
3. Get setting by key.

**Comment by oleksandr-jr** [comment]
Together with 33
