### ISSUE TITLE
[FR] Create a service class to access localized messages.

### ISSUE THREAD

**Issue by dRaider-bitrek** [JavaRush-GNEW/contact-manager#28]
## Description
Create a service class to access localized messages.
Do not fill in the properties file

Enter texts in *.properties files for each language.
Replace all hardcoded xnotifications

## Dependencies
- #24 
- #7 
- #16 

## Acceptance criteria
1. Create a service class

**Comment by dRaider-bitrek** [comment]
Ця таска завелика думаю її потрібно розбити на сворення механізмів інтенаціоналізвції та заповнення словників для кожнї мови.

**Comment by oleksandr-jr** [comment]
@dRaider-bitrek 

> Крім того тут є проблема. ResourceBundle наскільки розумію підтягує текст тільки у ISO 8859 -1 але це ломяє кірилицю. Можна руками підтянути і запхати йому файл в UTF -8. Але в мене IDE показує його краказябрами. :) А якщо зберегти, міняє формат на ANSI . Отже UTF-8 доводится редагувати в Notepad++ і не відкривати у IDE. Може є зручніший шлях? @oleksandr-jr
> 
> PS Схоже розібрався у налаштуваннях проекта стоїть ISO для файлів ресурсів. От тільки питання це ж я для себе тільки виправляю. Налаштування IDE на гіт же не підуть?
Де саме ти це знайшов?

Можете запушити .idea папку, але не все що там є. 
Серед конфігурацій там може бути кодування.
Ось тут є більше інформації.


https://keturn.net/blog/posts/2020/05/git-add-dot-idea-share-intellij/

https://www.toptal.com/developers/gitignore/api/pycharm

https://dev.to/snowe2010/comment/7kd1
