### ISSUE TITLE
[FR] Implement "add" and "search" methods for PhoneBookInterface

### ISSUE THREAD

**Issue by dRaider-bitrek** [JavaRush-GNEW/contact-manager#30]
## Description
Implement "add" and "search" methods for PhoneBookInterface.
Implement methods in SimplePhoneBook:
public ContactDto add(ContactDto contactDto);
public List<ContactDto> search(String str);

## Dependencies
- #16 
- #18 
- #20 
- #1 
- #35 

## Acceptance criteria
1. The methods should work according to #1

**Comment by DenysBurduzhan** [comment]
та же проблема, что и в прошлом тикете. По проекту: сделал возможность поиска по имени, телефону и почте
