### ISSUE TITLE
[FR] Implement data structure

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#4]
## Description:
Implement data structure described in this ticket #2 
But only entities like PhoneBook, email... 

## Dependencies:
#2 

## AC
AC:1 Data structure is implemented

**Comment by oleksandr-jr** [comment]
@dRaider-bitrek Managed to implement the mapstruct mapper and CI pipeline to run tests.

**Comment by dRaider-bitrek** [comment]
Якщо використовувати mapstruct мабуть довелется відмовитись ві інтерфейса Contact. Бо mapstruct  не вміє повертати інтерфейси. 
І мапрер здається стає занадто важливим, бо в ньому потрібно прописувати всю логіку перетворення між тим що ми даємо користувачу і що зберігаємо. Якщо щось міняєтся в збереженні це чипляє мапер.

**Comment by dRaider-bitrek** [comment]
Я пропоную залишити між CLI і реалізацією контакту інтерфес (це буде як контракт між ними)  а усі перетвореня (Email->String ...) робити на стороні реалізації.

**Comment by oleksandr-jr** [comment]
Тоді перетворення Email та Phone до string буде завжди вручну.
На мою думку, щось подібне до DTO так чи інакше буде імплементовано. Тоді чому не робити це так, як ми робимо це зазвичай.

Interface для Etity у цьому випадку вже не потрібно. DTO вже є свого роду інтерфейсом для Entity.

Якщо у вас є інше бачення, то просто змінюйте мій код в цьому PR :D

Можна тоді:
- Позбутися від класів Email / Phone взагалі [Найпростіший варіант]

**Comment by dRaider-bitrek** [comment]
ОК, працюємо з цим варіантом. Мабуть інтерфейс ContactEntity в цьому варіанті не буде використовуватись? 
Я не можу зробити review бо комітив?

**Comment by oleksandr-jr** [comment]
Так, треба, щоб хтось інший апрувнув
