### ISSUE TITLE
JavaRush badge

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#40]
## Description

Please add this JavaRush badge at the of the readme file.

[![JavaRush University](https://img.shields.io/badge/java-rush-orange?style=for-the-badge&color=orange&cacheSeconds=3600)](https://javarush.com/ua/university/)

```
[![JavaRush University](https://img.shields.io/badge/java-rush-orange?style=for-the-badge&color=orange&cacheSeconds=3600)](https://javarush.com/ua/university/)
```

## AC
1. The JavaRush badge has been added to the readme file.

**Comment by tojnya** [comment]
Added the JavaRush badge to README.md

**Comment by oleksandr-jr** [comment]
@tojnya 

- Checked 40-javarush-badge branch but did not find a badge in the readme, please check it.
- Please, create a pull request and move the ticket across the all states. Ready -> in progress -> ready for review ...

**Comment by oleksandr-jr** [comment]
@tojnya if you need any help / hints, feel free to ask the team in slack or reach me directly.

**Comment by tojnya** [comment]
Push failed. remote: Permission to JavaRush-GNEW/contact-manager.git denied to tojnya.
fatal: unable to access 'https://github.com/JavaRush-GNEW/contact-manager.git/': The requested URL returned error: 403
