### ISSUE TITLE
Research on the concept of data storage

### ISSUE THREAD

**Issue by oleksandr-jr** [JavaRush-GNEW/contact-manager#5]
Please, describe how data should be stored.
In files?
Where?
Data structure 
 - JSON? 

Encryption?

Resources:
Have a look at Java Jackson lib

AK1: Suggestions on how we can store information are provided

**Comment by dRaider-bitrek** [comment]
Оскільки додаток кожного разу фактично запускається з нуля. Тут не працюватимуть стратегії повязані з індексацією полів у оперативну пам'ять оскільки при виконнані кожної команди доведеться перечитувати весь файл. 

Тому пропоную:
 
**Варіант 1:** 
Зчитуємо файл. Тримаємо контакти у List<Contact>, при будь якій зміні сериалізуємо у JSON та переписуємо весь файл.

**Варіант 2:** 
Створюємо демона, запускаємо його як окремий процес перед виконнаям першої команди.
Зв'язок через сокет або http.
у демоні можна реалізувати складнішу систему зберігання з індексацією усіх полів та позиції запису у файлі.
Зберіганням індексів у окремих файлах аля таблиць у БД.
Або підтянути інмеморі базу щось типо H2.

**Варіант 3:**
Зробити rest сервіс з БД. Розмістити в облаці. Переренести туди зберігання пошук итд...

**Comment by dRaider-bitrek** [comment]
Тоді обираємо Варіант 1:

- Зчитуємо файл. Тримаємо контакти у List, при будь якій зміні сериалізуємо у JSON та переписуємо весь файл.
- Без шифрування.
- Для кожного користувача окремий файл.
- Поточний коритувач, обрана мова, та можливо інші налаштування зберігаємо в окремому файлі.

**Comment by DenysBurduzhan** [comment]
we are choosing 1st variant
