### ISSUE TITLE
Description and support for languages

### ISSUE THREAD

**Issue by DenysBurduzhan** [JavaRush-GNEW/contact-manager#7]
Describe how you can implement some languages ​​(ENG, RU, UKR...) in the program interface. 
Will we be able to change them at the request of users?

**Comment by dRaider-bitrek** [comment]
@DenysBurduzhan Як онова : https://javarush.com/ua/groups/posts/uk.1557.konstanti-ta-nternaconalzacja

**Comment by DenysBurduzhan** [comment]
Огромнейшее спасибо )))

**Comment by DenysBurduzhan** [comment]
https://lucid.app/lucidchart/f794aab5-8d85-4253-bad5-bc69462ddcbb/view

**Comment by DenysBurduzhan** [comment]
Такс, моя первая диаграмма. В дополнение к CLI структуре :
нужно добавить команды  --English/-en ; --Ukraine/-ukr ; --Russian/-ru ;
По умолчанию будет АНГЛ.

**Comment by DenysBurduzhan** [comment]
Мультиязычным будет как само меню , так и интерфейс пользователя. Сделаем через properties + класс ResourceBundle

**Comment by oleksandr-jr** [comment]
https://chatgpt.com/share/6724c3f1-c2b4-800a-a85f-524b238bcd0b

**Comment by dRaider-bitrek** [comment]
ОК тоді треба створити наступні таски:
1. Додати до CLI команду locale. Яка буде зберігати в налаштуваннях поточну локаль 
2. Створити службовий клас для доступу до локалізованих повідомлен.
3. Створити файли *.properties для кожної мови та замінити всі жорстко закодовані хсповіщення.

PS. Команда locale має зберігати поточну локаль через інерфейс SettingsRepository.

**Comment by dRaider-bitrek** [comment]
https://github.com/JavaRush-GNEW/contact-manager/pull/26#pullrequestreview-2410744958

**Comment by DenysBurduzhan** [comment]
Done
