### ISSUE TITLE
[BUG] Phones and emails arities in AddContact.java

### ISSUE THREAD

**Issue by tojnya** [JavaRush-GNEW/contact-manager#79]
## Describe the bug
In AddContact.java file, the `phones` variable `arity` is set to `0..3`. However, the `required` attribute is set to `true`, which makes the actual arity `1..3`. The `emails` variable has the same issue.

## To Reproduce
**Option 1**: leave `required = true` but set `arity = "1..3"`.
**Option 2**: leave `arity = "0..3"` but set `required = false`.

## Expected behaviour
**Case 1**: emails and phone numbers arity are fixed from '0..3' to '1..3'.
**Case 2**: emails and phone numbers are not required, so the program does not throw an exception in case they are missing.

## Screenshots
![Image](https://github.com/user-attachments/assets/bd145ac5-dbdc-45e1-9245-06b9c7e8d3f8)

**Comment by dRaider-bitrek** [comment]
Не тягніть на git файл testerbook.st. IDE потім свариться аж шкварчить. :)
